name: GitHub Release

on:
  push:
    tags:
      - "v*"
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Run Maven tests
        run: mvn test

  build:
    name: Build JAR
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./target

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Download Maven build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ~/build/
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ~/build/build-artifact/TimestampConverter-${{ env.VERSION }}-SNAPSHOT.jar
          asset_name: TimestampConverter-${{ env.VERSION }}-SNAPSHOT.jar
          asset_content_type: application/java-archive
